
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS sold_out boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS discount_percent numeric;

-- Seed catalog (idempotent). Image_url left empty so frontend can map to local asset by section.
INSERT INTO public.products (id, name, description, price, image_url, category, subcategory, customization, pair_unit, note, sort_order)
VALUES
  ('white-chicken','أبيض حي','فراخ بيضاء طازجة فريش',118,'','chicken','أبيض','chicken',false,NULL,10),
  ('baladi-chicken','بلدي حي','فراخ بلدي مذاق أصيل',140,'','chicken','بلدي','chicken',false,NULL,20),
  ('baladi-hor','بلدي حر','بلدي حر طبيعي',170,'','chicken','بلدي حر','chicken',false,NULL,30),
  ('omhat','فراخ أمهات','فراخ أمهات',0,'','chicken','أمهات','chicken',false,'اتصل لمعرفة السعر',40),
  ('duck-fallahi','بط فلاحي','بط فلاحي طازج',160,'','duck','بط فلاحي','duck',false,NULL,10),
  ('duck-moskovi','بط مسكوفي','بط مسكوفي طازج',160,'','duck','بط مسكوفي','duck',false,NULL,20),
  ('duck-cubes','مكعبات بط','مكعبات بط جاهزة (ميكس صدور ووراك)',290,'','duck','مكعبات','none',false,NULL,30),
  ('duck-breast','صدور بط','صدور بط طازجة',280,'','duck','صدور','none',false,NULL,40),
  ('duck-thigh','وراك بط','وراك بط طازج',280,'','duck','وراك','thigh-duck',false,NULL,50),
  ('turkey-white','رومي أبيض كامل','رومي أبيض كامل',160,'','turkey','رومي أبيض','none',false,NULL,10),
  ('turkey-baladi','رومي بلدي','رومي بلدي طازج',190,'','turkey','رومي بلدي','none',false,NULL,20),
  ('turkey-cubes','مكعبات رومي','مكعبات رومي (ميكس صدور ووراك)',200,'','turkey','مكعبات','none',false,NULL,30),
  ('rosto-turkey','روستو رومي','روستو رومي مميز',320,'','turkey','روستو','none',false,'الوزن من 1.5 إلى 2 كيلو - الطلب بالعدد',40),
  ('thigh-turkey','وراك رومي','وراك رومي طازج',190,'','turkey','وراك','none',false,'وزن الورك من 1.5 إلى 2 كيلو',50),
  ('pigeon','حمام بلدي','حمام بلدي طازج',220,'','pigeon','حمام','none',true,'الطلب بالجوز فقط',10),
  ('pigeon-rice','حمام محشي أرز','حمام محشي أرز جاهز',260,'','pigeon','حمام محشي','none',true,'الطلب بالجوز فقط',20),
  ('pigeon-freek','حمام محشي فريك','حمام محشي فريك جاهز',260,'','pigeon','حمام محشي','none',true,'الطلب بالجوز فقط',30),
  ('quail','سمان','سمان طازج',110,'','pigeon','سمان','none',true,'الطلب بالجوز فقط',40),
  ('shish-marinated','شيش متبل','شيش متبل جاهز للشواء',290,'','marinated',NULL,'none',false,NULL,10),
  ('shish-thigh-marinated','شيش متبل وراك','شيش وراك متبل',290,'','marinated',NULL,'none',false,NULL,20),
  ('shish-breast-marinated','شيش متبل صدور','شيش صدور متبل',290,'','marinated',NULL,'none',false,NULL,30),
  ('kofta-chicken','كفتة فراخ','كفتة فراخ متبلة',290,'','marinated',NULL,'none',false,NULL,40),
  ('strips','ستربس متبل','ستربس فراخ متبل',290,'','marinated',NULL,'none',false,NULL,50),
  ('panee-marinated','بانية متبل','بانية متبل',290,'','marinated',NULL,'none',false,NULL,60),
  ('nuggets','ناجتس','ناجتس فراخ',300,'','marinated',NULL,'none',false,NULL,70),
  ('crispy','كرسبي','قطع كرسبي',300,'','marinated',NULL,'none',false,NULL,80),
  ('kofta-rice-meat','كفتة أرز ولحم','كفتة أرز ولحم',400,'','marinated',NULL,'none',false,NULL,90),
  ('fake-pigeon','جوز حمام كذاب','حمام كذاب',140,'','marinated',NULL,'none',false,NULL,100),
  ('sausage-chicken','سجق فراخ','سجق فراخ متبل',290,'','marinated',NULL,'none',false,NULL,110),
  ('cordon-bleu','كوردون بلو','كوردون بلو',300,'','marinated',NULL,'none',false,NULL,120),
  ('stuffed-rice-white','فرخة أبيض محشية أرز','فرخة محشية أرز',260,'','marinated',NULL,'none',false,NULL,130),
  ('stuffed-baladi-freek','فرخة بلدي محشية فريك','فرخة بلدي محشية فريك',290,'','marinated',NULL,'none',false,NULL,140),
  ('marinated-thermal','فراخ متبلة حراري','فراخ متبلة حراري',260,'','marinated',NULL,'none',false,NULL,150),
  ('thigh-tray','صينية وراك متبلة','صينية وراك متبلة',180,'','marinated',NULL,'none',false,NULL,160),
  ('mombar','ممبار','ممبار محشي',145,'','marinated',NULL,'none',false,NULL,170),
  ('grape-leaves','ورق عنب','ورق عنب محشي',125,'','marinated',NULL,'none',false,NULL,180),
  ('cabbage','محشي كرنب','محشي كرنب',125,'','marinated',NULL,'none',false,NULL,190),
  ('kofta-panee','كفتة بانية','كفتة بانية',0,'','marinated',NULL,'none',false,'اتصل لمعرفة السعر',200),
  ('shawerma','شاورما عادية','شاورما فراخ',170,'','marinated',NULL,'none',false,NULL,210),
  ('wing','جناح','أجنحة فراخ',60,'','parts',NULL,'none',false,NULL,10),
  ('ground','مفروم','فراخ مفروم',170,'','parts',NULL,'none',false,NULL,20),
  ('breast-bone','صدور بالعظم','صدور بالعظم',230,'','parts',NULL,'breast-bone',false,'الطلب بالعدد فقط — وزن الصدر حوالي 600 إلى 800 جرام',30),
  ('breast-bone-baladi','صدور بالعظم بلدي','صدور بلدي بالعظم',289,'','parts',NULL,'breast-bone',false,'الطلب بالعدد فقط — وزن الصدر حوالي 600 إلى 800 جرام',40),
  ('shish','شيش','شيش طازج',252,'','parts',NULL,'none',false,NULL,50),
  ('panee','بانية','بانية فراخ',259,'','parts',NULL,'none',false,NULL,60),
  ('thigh-bone','وراك بالعظم','وراك بالعظم',107,'','parts',NULL,'thigh-bone',false,NULL,70),
  ('thigh-bone-baladi','وراك بالعظم بلدي','وراك بلدي بالعظم',130,'','parts',NULL,'thigh-bone',false,NULL,80),
  ('dababees','دبابيس','دبابيس فراخ',195,'','parts',NULL,'dababees',false,NULL,90),
  ('liver','كبدة','كبدة فراخ',135,'','parts',NULL,'none',false,NULL,100),
  ('qawanis','قوانص','قوانص فراخ',110,'','parts',NULL,'none',false,NULL,110),
  ('liver-qawanis','كبد وقوانص (مشكل)','كبدة وقوانص ميكس',123,'','parts',NULL,'none',false,NULL,120),
  ('fakhayed','فخايد','فخايد فراخ',100,'','parts',NULL,'fakhayed',false,NULL,130),
  ('rabbit','أرانب','أرانب طازجة مختارة بعناية',147,'','other',NULL,'rabbit',false,NULL,10)
ON CONFLICT (id) DO NOTHING;
